[workspace]
resolver = "2"
members = [ 
    "base", 
    "boot", 
    "linker", 
    "macro",
    "pagetable",
    "polyhal"
]
exclude = [
    "example"
]

[workspace.dependencies]
polyhal-base = { path = "./base" }
polyhal-boot = { path = "./boot" }
polyhal-linker = { path = "./linker" }
polyhal-macro = { path = "./macro" }
polyhal-pagetable = { path = "./pagetable" }
