[package]
name = "polyhal"
version = "0.1.3"
edition = "2021"
description = "This crate provides the interface for multiple platforms."
authors = ["yfblock@321353225@qq.com"]
license = "MIT"
repository = "https://github.com/Byte-OS/polyhal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
kcontext = []
multicore = ["boot"]
trap = []
boot = []
logger = []

vga_text = []
graphic = []

default = ["boot", "kcontext"]

[dependencies]
log = "0.4"
fdt = "0.1.5"
bitflags = "2.0.2"
cfg-if = "1.0.0"
polyhal-macro = "0.1.3"
spin = { version = "0.9.8", features = ["mutex"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.11.0"
sbi-rt = { version = "0.0.2", features = ["legacy"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86 = "0.52"
x86_64 = "0.14"
multiboot = "0.8.0"
x2apic = "0.4"
raw-cpuid = "11.0"

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "9.3"
arm_pl011 = "0.1.0"
tock-registers = "0.8"
arm_gicv2 = "0.1.0"

[target.'cfg(target_arch = "loongarch64")'.dependencies]
loongArch64 = "0.2.2"

[dev-dependencies]
buddy_system_allocator = "0.9.1"

[patch.crates-io.polyhal-macro]
path = "polyhal-macro"
