[toolchain]
profile = "minimal"
channel = "nightly-2025-02-01"
components = [
  "rust-src",
  "rustfmt",
  "clippy",
  "rust-analyzer",
  "llvm-tools-preview",
]
targets = [
  "riscv64imac-unknown-none-elf",
  "riscv64gc-unknown-none-elf",
  "x86_64-unknown-none",
  "aarch64-unknown-none-softfloat",
  "loongarch64-unknown-none",
]
