# Just used for rust-analyzer.
[build]
target = "riscv64gc-unknown-none-elf"
# target = 'aarch64-unknown-none-softfloat'
# target = 'x86_64-unknown-none'
# target = 'loongarch64-unknown-none'

[target.'cfg(target_os = "none")']
runner = "./test.sh"
rustflags = [
    "-Clink-arg=-Texample/linker/linker-riscv64.ld",
    "-Cforce-frame-pointers=yes",
    '--cfg=board="qemu"',
]
